// File generated by FlutterFire CLI. You'll need to run:
// flutter pub add firebase_core
// dart pub global activate flutterfire_cli
// flutterfire configure

// For now, this is a placeholder. After running 'flutterfire configure',
// this file will be automatically generated with your Firebase config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASKrF21s-hJKKS15OjUWXSpccIbtkXKEE',
    appId: '1:771467428266:android:df4d510ea404ba8a33abd3',
    messagingSenderId: '771467428266',
    projectId: 'mental-healthmonitor',
    databaseURL: 'https://mental-healthmonitor-default-rtdb.firebaseio.com',
    storageBucket: 'mental-healthmonitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaFqr1Ajv0L6EqR4Qmu-tq_-3fQcBIYTI',
    appId: '1:771467428266:ios:5d491ebf11ab68f933abd3',
    messagingSenderId: '771467428266',
    projectId: 'mental-healthmonitor',
    databaseURL: 'https://mental-healthmonitor-default-rtdb.firebaseio.com',
    storageBucket: 'mental-healthmonitor.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw052QZi_Y0mmm3aSSz15_FU30mbXeU0g',
    appId: '1:771467428266:web:e5f53cc1ac3443b633abd3',
    messagingSenderId: '771467428266',
    projectId: 'mental-healthmonitor',
    authDomain: 'mental-healthmonitor.firebaseapp.com',
    databaseURL: 'https://mental-healthmonitor-default-rtdb.firebaseio.com',
    storageBucket: 'mental-healthmonitor.firebasestorage.app',
    measurementId: 'G-FQEYSEV4H5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaFqr1Ajv0L6EqR4Qmu-tq_-3fQcBIYTI',
    appId: '1:771467428266:ios:5d491ebf11ab68f933abd3',
    messagingSenderId: '771467428266',
    projectId: 'mental-healthmonitor',
    databaseURL: 'https://mental-healthmonitor-default-rtdb.firebaseio.com',
    storageBucket: 'mental-healthmonitor.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw052QZi_Y0mmm3aSSz15_FU30mbXeU0g',
    appId: '1:771467428266:web:09fb80fd63a7a21333abd3',
    messagingSenderId: '771467428266',
    projectId: 'mental-healthmonitor',
    authDomain: 'mental-healthmonitor.firebaseapp.com',
    databaseURL: 'https://mental-healthmonitor-default-rtdb.firebaseio.com',
    storageBucket: 'mental-healthmonitor.firebasestorage.app',
    measurementId: 'G-B0K4RYG993',
  );

}